apiVersion: v1
kind: Pod
metadata:
  name: nginx-secret
spec: 
  volumes:
    - name: k8s-login-secret              # marking a secret as a volume
      secret:
        secretName: login-secret
  containers:
    - name: nginx-c
      image: nginx:alpine
      env:
        - name: LOGIN_SECRET_USERNAME     # putting secret values as env variables
          valueFrom: 
            secretKeyRef:
              name: login-secret
              key: username
      env:
        - name: LOGIN_SECRET_PASSWORD
          valueFrom: 
            secretKeyRef:
              name: login-secret
              key: password
      volumeMounts:
        - name: k8s-login-secret          # mounting a secret to the file system
          mountPath: /etc/logins
          readOnly: true
