apiVersion: apps/v1
kind: Deployment
metadata:
  name: catissimo-be
  labels:
    app: catissimo
    tier: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: catissimo
      tier: backend
  template:
    metadata:
      labels:
        app: catissimo
        tier: backend 
    spec:
      containers:
        - name: be-nginx
          image: nginx:alpine
          ports:
          - containerPort: 80

