apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: my-nginx
    tier: frontend
spec:                 # top-level specification
  #replicas: 1        # scaling but it is disblaed for testing, because this will override any manual commands
  selector:           # selector for a template that can be in a separate file, but it's typically not
    matchLabels:
      tier: frontend  # label 'tier' with the value 'frontend'
  template:           # the template that is selected with the selector above
    metadata:
      labels:
        tier: frontend  # repeated here because this template could be in its own separate file
    spec:               # specification for pods defined in the template
      containers:
      - name: my-nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: "128Mi"
            cpu: "200m"     # 200 millicpu (.2 or 20% of the cpu)
