apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: my-nginx
    tier: frontend
spec:                 # top-level specification
  selector:           # selector for a template that can be in a separate file, but it's typically not
    matchLabels:
      tier: frontend  # label 'tier' with the value 'frontend'
  template:           # the template that is selected with the selector above
    metadata:
      labels:
        tier: frontend  # repeated here because this template could be in its own separate file
    spec:               # specification for pods defined in the template
      containers:
      - name: my-nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
