apiVersion: v1
kind: Pod
metadata:
  name: nginx-configmap
spec: 
  volumes:
    - name: userconfig-env
      configMap:
        name: user-settings-yaml          # 1. Mounting config file as volume
  containers:
    - name: nginx-c
      image: nginx:alpine
      env:
      - name: CLI_ENV
        valueFrom: 
          configMapKeyRef:
            name: userconfig-cli          # 2. Extracting specific key-value pairs from a config
            key: appName
      envFrom:                            # 3. Loading whole configuration into env
      - configMapRef:
          name: userconfig
      volumeMounts:
        - name: userconfig-env
          mountPath: /etc/user-config
