apiVersion: apps/v1
kind: Deployment
metadata:
  name: catissimo
  labels:
    app: catissimo
spec:
  replicas: 3
  minReadySeconds: 1
  progressDeadlineSeconds: 60
  revisionHistoryLimit: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
      matchLabels:
        app: catissimo
  template:
    metadata:
      labels:
        app: catissimo
    spec:
      containers:
      - name: ccon-v2
        image: catissimo:2.0          # Image bump for v2
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: "200m"
            memory: "128Mi"
