apiVersion: v1
kind: Pod
metadata:
  name: exec-liveness-nginx
spec:
  containers:
    - name: exec-liveness-nginx
      image: nginx:alpine
      args:
      - /bin/sh
      - -c
      - |
        touch /tmp/healthy    # make the pod available by creating expected file (see liveness below)
        sleep 5               # and after 5 seconds
        rm -rf /tmp/healthy   # delete it to simulate failure
        sleep infinity        # and keep the container up until failure is detected
      livenessProbe:
        exec:
          command:
          - cat
          - /tmp/healthy
        initialDelaySeconds: 1
        timeoutSeconds: 2
        periodSeconds: 3
        failureThreshold: 1
