apiVersion: v1
kind: Pod
metadata:
  name: yaml-nginx
spec:
  containers:
    - name: yaml-nginx
      image: nginx:alpine
      readinesProbe:
        httpGet:
          path: /index.html
          port: 80
        initialDelaySeconds: 2
        periodSeconds: 5
