apiVersion: v1
kind: Pod
metadata:
  name: http-liveness-nginx
spec:
  containers:
    - name: http-liveness-nginx
      image: nginx:alpine
      livenessProbe:
        httpGet:
          path: /index.html
          port: 80
        initialDelaySeconds: 2    # liveness checks start after 2s
        timeoutSeconds: 2         # timeout after 2 seconds
        periodSeconds: 3          # check every 5 seconds
