apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: big-local-storage-pvc
spec:
  storageClassName: local-storage
  accessModes:
  - ReadOnlyMany
  resources:
    requests:
      storage: 200Mi
