apiVersion: v1
kind: PersistentVolume
metadata:
  name: small-local-pv
spec:
  capacity:
    storage: 50Mi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /tmp/persistent-storage
  nodeAffinity:
    required:
      nodeSelectorTerms:      
      - matchExpressions:
        - key: kubernetes.io/hostname    
          operator: In
          values:
          - minikube 
