apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: small-local-storage-pvc
spec:
  storageClassName: local-storage
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Mi
