apiVersion: rbac.authorization.k8s.io/v1    # obtained via kubectl api-versions
kind: Role
metadata:
  namespace: default
  name: basic-svc-role
rules:
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1  # same here
kind: RoleBinding
metadata:
  namespace: default
  name: basic-svc-binding
subjects:
- kind: ServiceAccount
  name: "service-reader"
  namespace: default 
roleRef:
  kind: Role
  name: basic-svc-role
  apiGroup: rbac.authorization.k8s.io
