apiVersion: v1
kind: Pod
metadata:
  name: volume-test
spec:
  containers:
  - name: volume-test
    image: busybox
    imagePullPolicy: IfNotPresent
    volumeMounts:
    - name: volv
      mountPath: /data
    ports:
    - containerPort: 80
    command: ['/bin/sh', '-c']
    args: ['echo Meow! $(date) > /data/meow && sleep infinity']
  volumes:
  - name: volv
    persistentVolumeClaim:
      claimName: local-path-pvc

