apiVersion: batch/v1      # notice the uncommon version type
kind: Job
metadata:
  name: parallel-job
spec:
  parallelism: 5           # ran pods at in parallel
  completions: 20          # specify required number of completed to succeed
  template:
    metadata:
      name: parallel-job-pod
      labels:
        type: parallel-job
    spec:
      restartPolicy: Never    # or OnFailure
      containers:
      - name: pjp-c
        image: alpine
        command:
        - /bin/sh
        - -c
        - "echo `hostname`: `date`"
