apiVersion: apps/v1
kind: Deployment
metadata:
  name: fur
spec:
  replicas: 10
  selector:
    matchLabels:
      app: fur
  template:
    metadata:
      labels:
        app: fur
    spec:
      containers:
      - name: f-cont
        image: busybox
        command: ['sleep']
        args: ['infinity']
      # deployment spread throughout the cluster
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              topologyKey: "kubernetes.io/hostname"
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - fur
