apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{.Chart.Name}}-ingress
spec:
  rules:
  - host: backend.minikube.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: be-service
            port: 
              number: {{.Values.ports.external}}
