apiVersion: apps/v1
kind: Deployment
metadata:
  name: catissimo-stable
  labels:
    app: catissimo
    track: stable
spec:
  replicas: 4
  selector:
      matchLabels:
        app: catissimo
        track: stable
  template:
    metadata:
      labels:
        app: catissimo
        track: stable
    spec:
      containers:
      - name: stable-cont
        image: catissimo:1.0
        resources:
          limits:
            cpu: "200m"
            memory: "128Mi"
