apiVersion: v1
kind: Pod
metadata:
  name: configured-pod
spec:
  containers:
    - name: bp-cont
      image: busybox
      command: ["sleep"]
      args: ["1000"]
  dnsPolicy: "None"
  dnsConfig:
    nameservers:
      - 9.9.9.9
