apiVersion: apps/v1
kind: Deployment
metadata:
  name: emptydir-deployment
spec:
  selector:
    matchLabels:
      app: emptydir
  template:
    metadata:
      labels:
        app: emptydir
    spec:
      volumes: 
        - name: html                         # has to be unique
          emptyDir: {}
      containers:
        - name: paw
          image: nginx:alpine
          volumeMounts:
            - name: html
              mountPath: /usr/share/nginx/html
              readOnly: true
          resources:
        - name: html-updater
          image: alpine
          command: ["/bin/sh", "-c"]
          args:
            - echo 'starting...' > /html/index.html;
              while true; do 
                date >> /html/index.html;
                sleep 5; 
              done
          volumeMounts:
            - name: html
              mountPath: /html
          resources:
