apiVersion: v1
kind: Pod
metadata:
  name: emptydir-pod
spec:
  volumes: 
    - name: html                         # has to be unique
      emptyDir: {}
  containers:
    - name: paw
      image: nginx:alpine
      volumeMounts:
        - name: html
          mountPath: /usr/share/nginx/html
          readOnly: true
      resources:
    - name: html-updater
      image: alpine
      command: ["/bin/sh", "-c"]
      args:
        - while true; do 
            date >> /html/index.html;
            echo '<br/>' >> /html/index.html;
            sleep 1; 
          done
      volumeMounts:
        - name: html
          mountPath: /html
      resources:
