apiVersion: v1
kind: Pod
metadata:
  name: hostpath-pod
spec:
  volumes: 
    - name: docker-socket
      hostPath:
        path: /var/run/docker.sock
        type: Socket
  containers:
    - name: meow
      image: docker
      volumeMounts:
        - name: docker-socket
          mountPath: /var/run/docker.sock
          readOnly: true
      command: ["sleep"]                    # just to keep the container running
      args: ["1000"]
      resources:
