apiVersion: v1
kind: Pod
metadata:
  name: singular-pod
spec:
  volumes:
  - name: local-storage
    persistentVolumeClaim: 
      claimName: local-sc-pvc
  containers:
    - name: thy-server
      image: nginx:alpine
      command:
        - /bin/sh
        - -c
        - touch /tmp/data/logs && echo $(date) >> /tmp/data/logs && sleep infinity
      volumeMounts:
      - name: local-storage
        mountPath: /tmp/data
      resources:
      
