apiVersion: v1
kind: Pod
metadata:
  name: singular-pod-copy
spec:
  volumes:
  - name: thy-storage-copy
    persistentVolumeClaim: 
      claimName: local-storage-pvc
  containers:
    - name: thy-server-copy
      image: nginx:alpine
      command:
        - /bin/sh
        - -c
        - date >> /tmp/data/logs && sleep 1000
      volumeMounts:
      - name: thy-storage-copy
        mountPath: /tmp/data
      resources:
      
