apiVersion: v1
kind: Pod
metadata:
  name: singular-pod
spec:
  volumes:
  - name: thy-storage
    persistentVolumeClaim: 
      claimName: local-storage-pvc
  containers:
    - name: thy-server
      image: nginx:alpine
      command:
        - /bin/sh
        - -c
        - date >> /tmp/data/logs && sleep 1000
      volumeMounts:
      - name: thy-storage
        mountPath: /tmp/data
      resources:
      
