apiVersion: apps/v1
kind: Deployment
metadata:
  {{- $ChartName := .Chart.Name }}
  {{- with .Values }}
  name: {{ $ChartName }}
  labels:
    app: {{.name}}
    tier: frontend
    rendString: 
spec:
  replicas: 2
  selector:
    matchLabels:
      app: {{.name}}
      tier: frontend
  template:
    metadata:
      labels:
        app: {{.name}}
        tier: frontend 
  {{- end }}
    spec:
      containers:
        - name: fe-nginx
          image: nginx:alpine
          command:
          - /bin/sh
          - -c
          - >
            while true; do
              echo 'Release Name: {{.Release.Name}}' > /usr/share/nginx/html/index.html;
              echo '{{.Values.greeting}}' >> /usr/share/nginx/html/index.html;
              echo '</hr >' >> /usr/share/nginx/html/index.html;
              echo 'Random Word: {{ randAlphaNum 20 | trunc 15 | trimSuffix "-" }}' >> /usr/share/nginx/html/index.html;
              echo 'Base64 encoded password: {{.Values.password | b64enc | quote}}' >> /usr/share/nginx/html/index.html;
              echo 'Test: {{ printf "- %s" .Values.global.owner | indent 4 }}' >> /usr/share/nginx/html/index.html;
              echo 'By {{.Values.global.owner}}' >> /usr/share/nginx/html/index.html;
              sleep 300;
            done
          ports:
          - containerPort: {{.Values.ports.internal}}

