apiVersion: v1
kind: Pod
metadata:
  name: cat-servant
  labels:
    app: catness
spec:
  initContainers:
    - name: wait-for-svc-container
      image: busybox
      imagePullPolicy: IfNotPresent
      # due to busybox error we need to provide full DNS entry for our service
      # see the bug: https://bugs.busybox.net/show_bug.cgi?id=14671
      # Otherwise we would only call "nslookup cat-heaven"
      command:
        - sh
        - -c 
        - >
          until nslookup cat-heaven.default.svc.cluster.local 1>/dev/null; do
            date | tr -d "\n" &&
            echo ": Waiting for catheaven service to be accessible...";
            sleep 1;
          done;
          echo "Service found and available!"
  containers:
    - name: main-app
      image: nginx:alpine
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 8080
      resources:
        limits:
          cpu: "200m"
          memory: "50Mi"
