apiVersion: v1
kind: Pod
metadata:
  name: multicontainer-pod
spec:
  containers:
    - name: nginx
      image: nginx:alpine
    - name: bb
      image: busybox
      command: ['/bin/sh']
      args: ['-c', 'sleep infinity']
