apiVersion: v1
kind: ConfigMap
metadata:
  name: be-html
  labels:
    app: {{.Values.name}}
    tier: backend
data:
  # not a real use case :)
  index.html: |
    <!DOCTYPE html>
    <html lang="en">
      <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Helm Templating</title>
      </head>
      <body>
        <h1>You did it!</h1>
        <p>Custom templating done with Helm. On an NGINX server. Bravo!</p>
        <p>Release Name: {{.Release.Name}}</p>
        <p>{{ quote .Values.greeting}}</p>
        </hr>
        <p>By {{.Values.global.owner}}</p>
      </body>
    </html>
