apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Chart.Name}}
  labels:
    app: {{.Values.name}}
    tier: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: {{.Values.name}}
      tier: backend
  template:
    metadata:
      labels:
        app: {{.Values.name}}
        tier: backend 
    spec:
      volumes:
        - name: html
          configMap:
            name: be-html
      containers:
        - name: be-nginx
          image: nginx:alpine
          volumeMounts:
          - name: html
            mountPath: /usr/share/nginx/html
          ports:
          - containerPort: {{.Values.ports.internal}}

