apiVersion: v1
kind: Service
metadata:
  name: be-service
spec:
  selector:
    app: {{.Values.Name}}
    tier: backend
  ports:
    - protocol: TCP
      port: {{.Values.ports.internal}}
      targetPort: {{.Values.ports.external}}
